# Generated by Django 4.2.2 on 2024-10-26 06:07

from django.db import migrations, models
import files.models
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0004_media_body_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='media',
            name='logo_image',
            field=imagekit.models.fields.ProcessedImageField(
                blank=True, help_text='This image will be placed above the body text.', max_length=500, upload_to=files.models.logo_thumbnail_file_path, verbose_name='Upload Logo Image'
            ),
        ),
        migrations.AddField(
            model_name='media',
            name='special_state',
            field=models.CharField(choices=[('normal', 'Normal Media'), ('topimage', 'Top Image, Body Text')], db_index=True, default='normal', help_text='Create composited media.', max_length=100),
        ),
        migrations.AddField(
            model_name='media',
            name='top_image',
            field=imagekit.models.fields.ProcessedImageField(
                blank=True, help_text='This image will be placed above the body text.', max_length=500, upload_to=files.models.top_thumbnail_file_path, verbose_name='Upload Top Image'
            ),
        ),
        migrations.AlterField(
            model_name='media',
            name='state',
            field=models.CharField(choices=[('private', 'Private'), ('public', 'Public'), ('unlisted', 'Unlisted')], db_index=True, default='public', help_text='state of Media.', max_length=20),
        ),
    ]
