# Generated by Django 4.2.2 on 2024-10-26 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0005_media_logo_image_media_special_state_media_top_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='playlist',
            name='end_date',
            field=models.DateTimeField(auto_now_add=True, db_index=True, help_text='end date', null=True),
        ),
        migrations.AddField(
            model_name='playlist',
            name='end_time',
            field=models.DateTimeField(auto_now_add=True, db_index=True, help_text='end time', null=True),
        ),
        migrations.AddField(
            model_name='playlist',
            name='start_date',
            field=models.DateTimeField(auto_now_add=True, db_index=True, help_text='start date', null=True),
        ),
        migrations.AddField(
            model_name='playlist',
            name='start_time',
            field=models.DateTimeField(auto_now_add=True, db_index=True, help_text='start time', null=True),
        ),
    ]
