# Generated by Django 4.2.2 on 2024-10-26 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0006_playlist_end_date_playlist_end_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='playlist',
            name='playlist_play_type',
            field=models.CharField(
                choices=[('normal', 'Normal'), ('schedueleddate', 'Schedueled Date Range'), ('schedueledtime', 'Schedueled Time'), ('schedueleddatetime', 'Schedueled Date Time Range')],
                db_index=True,
                default='normal',
                max_length=100,
            ),
        ),
    ]
