# Generated by Django 4.2.2 on 2024-10-26 22:24

from django.db import migrations, models
import files.models
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0007_playlist_playlist_play_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='media',
            name='font_align',
            field=models.CharField(choices=[('center', 'Cener'), ('left', 'Left'), ('right', 'Right')], default='center', help_text='Font align for the body text', max_length=20),
        ),
        migrations.AddField(
            model_name='media',
            name='font_bold',
            field=models.BooleanField(default=True, help_text='Font bold for the body text'),
        ),
        migrations.AddField(
            model_name='media',
            name='font_size',
            field=models.IntegerField(default=20, help_text='Font size for the body text'),
        ),
        migrations.AlterField(
            model_name='media',
            name='logo_image',
            field=imagekit.models.fields.ProcessedImageField(
                blank=True, help_text='This image will be placed behind your main media.', max_length=500, upload_to=files.models.logo_thumbnail_file_path, verbose_name='Upload BG Image'
            ),
        ),
    ]
