# Generated by Django 4.2.2 on 2024-10-26 22:37

from django.db import migrations, models
import files.models
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0009_media_background_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='media',
            name='font_color',
            field=models.CharField(default='#000000', help_text='Font color for the body text', max_length=200),
        ),
        migrations.AlterField(
            model_name='media',
            name='background_image',
            field=imagekit.models.fields.ProcessedImageField(
                blank=True, help_text='This image will be placed above the body text.', max_length=500, upload_to=files.models.background_image_file_path, verbose_name='Upload Background Image'
            ),
        ),
    ]
