# Generated by Django 4.2.2 on 2024-10-27 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0010_media_font_color_alter_media_background_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='media',
            name='content_size_scale',
            field=models.IntegerField(default=100, help_text='Scale the content size in percentage'),
        ),
        migrations.AddField(
            model_name='media',
            name='flex_direction',
            field=models.CharField(choices=[('row', 'Row'), ('column', 'Column')], default='column', help_text='Flex direction for the content over the background', max_length=20),
        ),
        migrations.AddField(
            model_name='media',
            name='padding_content',
            field=models.IntegerField(default=50, help_text='Padding in pixels for the content over the background'),
        ),
    ]
