# Generated by Django 4.2.2 on 2024-10-27 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0011_media_content_size_scale_media_flex_direction_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='media',
            name='aspect_ratio',
            field=models.CharField(
                choices=[('original', 'Original'), ('16:9', '16:9'), ('4:3', '4:3'), ('1:1', '1:1'), ('3:4', '3:4'), ('9:16', '9:16')],
                default='original',
                help_text='Force aspect ratio for the media',
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name='media',
            name='special_state',
            field=models.CharField(
                choices=[('normal', 'Normal Media'), ('topimage', 'Top Image, Body Text')],
                db_index=True,
                default='normal',
                help_text='Create different types of content based on the input media by setting this state.',
                max_length=100,
            ),
        ),
    ]
